### ISSUE TITLE
Data transfer

### ISSUE THREAD

**Issue by 12skoko** [TDCPF/hath#1]
I have been running hah in Linux for a while now. Can I transfer data and resources directly to Docker？

**Comment by NotExist** [comment]
Sorry for lately response since I didn't realize there's user here (you opened the very first issue!)

> I have been running hah in Linux for a while now. Can I transfer data and resources directly to Docker？

Yes! I can't be sure what "data and resources" you refer to but "cache" and "archive download" (which can prevent re-download if you place them where they downloaded) can be loaded with docker instance with no pain if you configure docker volume correctly. For the credentials, you can migrate them if you're familiar with file-operation-in-and-out-container but I think copy&paste is far less pain.

I'll close this since it had been a while (and you might get it done already...), but it's welcome to reopen it if you need any help/discussion, thanks!
